name: Build APK
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK
      run: |
        echo "Installing Android SDK..."
        # 设置SDK版本
        SDK_VERSION="34"
        BUILD_TOOLS_VERSION="34.0.0"
        
        # 设置基础路径
        export ANDROID_HOME=/usr/local/lib/android/sdk
        export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
        
        # 添加SDK工具到PATH
        export PATH="${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${PATH}"
        
        # 创建必要的目录
        mkdir -p "${ANDROID_HOME}/licenses"
        
        # 添加许可证
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "${ANDROID_HOME}/licenses/android-sdk-license"
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "${ANDROID_HOME}/licenses/android-sdk-license"
        
        # 安装SDK组件
        yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null 2>&1
        echo "Installing SDK components..."
        ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" \
            "platforms;android-${SDK_VERSION}" \
            "build-tools;${BUILD_TOOLS_VERSION}" \
            "cmake;3.22.1" \
            --verbose
            
        # 导出环境变量
        {
            echo "ANDROID_HOME=${ANDROID_HOME}"
            echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}"
            echo "PATH=${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${PATH}"
        } >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel setuptools
        python -m pip install --upgrade cython==3.0.2
        python -m pip install --upgrade kivy==2.2.1
        python -m pip install --upgrade pillow==10.0.0
        python -m pip install --upgrade buildozer==1.5.0
        python -m pip install --upgrade python-for-android
        
        # 安装项目依赖
        pip install -r requirements.txt || true  # 忽略错误，因为某些依赖可能已经安装
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          libpangoft2-1.0-0 \
          libjpeg-dev \
          libfreetype6-dev \
          gcc \
          make \
          openjdk-17-jdk

    - name: Cache NDK
      uses: actions/cache@v4
      with:
        path: ~/.buildozer/android/platform/android-ndk-r25b
        key: ndk-r25b-cache

    - name: Set NDK environment variables
      run: |
        # 统一NDK路径配置
        NDK_HOME="/home/runner/.buildozer/android/platform/android-ndk-r25b"
        echo "ANDROID_NDK_HOME=${NDK_HOME}" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=${NDK_HOME}" >> $GITHUB_ENV
        echo "ANDROIDNDK=${NDK_HOME}" >> $GITHUB_ENV
        
        # 确保目录存在
        mkdir -p ${NDK_HOME}

    - name: Build APK with detailed logging
      run: |
        echo "Starting APK build with detailed logging..."
        echo "Python version:"
        python --version
        echo "Buildozer version:"
        buildozer --version
        echo "Environment variables:"
        env | grep ANDROID
        echo "JAVA_HOME=$JAVA_HOME"
        
        # 检查Python依赖
        python -c "import kivy; print('Kivy version:', kivy.__version__)"
        python -c "from PIL import Image; print('Pillow version:', Image.__version__)"
        python -c "import cython; print('Cython version:', cython.__version__)"
        
        # 显示项目结构
        echo "Project structure:"
        ls -la
        
        # 清理之前的构建（如果有）
        rm -rf .buildozer/android/platform/build-*
        
        # 使用详细日志构建
        echo "开始构建APK..."
        buildozer android debug -v --verbose | tee buildozer.log
        BUILD_RESULT=$?
        
        echo "构建完成，检查构建结果..."
        echo "Build result code: $BUILD_RESULT"
        
        # 显示详细日志
        echo "显示buildozer日志末尾:"
        tail -n 200 buildozer.log
        
        # 搜索所有可能的日志文件
        echo "搜索所有日志文件:"
        find . -name "*.log" -type f -exec echo "Found log file: {}" \; -exec tail -n 50 {} \;
        
        # 搜索APK文件
        echo "搜索APK文件:"
        find . -name "*.apk" -type f -print
        
        # 显示构建目录结构
        echo "显示构建目录结构:"
        ls -R .buildozer/android/ 2>/dev/null || echo ".buildozer/android/目录不存在"
        
        # 如果构建失败，显示更多调试信息
        if [ $BUILD_RESULT -ne 0 ]; then
          echo "构建失败。显示更多调试信息:"
          echo "当前目录内容:"
          ls -la
          echo ".buildozer目录内容:"
          ls -la .buildozer 2>/dev/null || echo ".buildozer目录不存在"
          exit 1
        else
          echo "构建成功。"
        fi

    - name: Locate and Upload APK
      run: |
        echo "正在搜索并上传APK文件..."
        
        # 创建上传目录
        mkdir -p apks
        
        # 搜索所有APK文件并复制到上传目录
        echo "查找所有APK文件..."
        find . -name "*.apk" -type f -print
        find . -name "*.apk" -type f -exec cp {} apks/ \;
        
        # 检查是否找到APK文件
        if [ "$(ls -A apks)" ]; then
          echo "找到以下APK文件:"
          ls -la apks/
        else
          echo "未找到APK文件"
          echo "显示构建目录内容："
          ls -R .buildozer/ 2>/dev/null || echo ".buildozer目录不存在"
          
          # 搜索可能的APK文件位置
          echo "在更多位置搜索APK文件:"
          find . -type f -name "*.apk" -o -name "*buildozer*" | head -20
          
          # 创建一个包含详细构建信息的文件
          echo "Build completed at: $(date)" > build_result.txt
          echo "Build result: No APK generated" >> build_result.txt
          echo "Debug information:" >> build_result.txt
          echo "Current directory: $(pwd)" >> build_result.txt
          echo "Directory contents:" >> build_result.txt
          ls -la >> build_result.txt
          echo ".buildozer contents:" >> build_result.txt
          ls -la .buildozer >> build_result.txt 2>&1 || echo ".buildozer directory does not exist" >> build_result.txt
        fi

    - name: Upload Build Results
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: |
          apks/
          build_result.txt
          buildozer.log
        retention-days: 90
        if-no-files-found: ignore